#!/bin/bash
kerasAC_train \
    --batch_size 50 \
    --ref_fasta s3://encode-refs/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta \
    --tdb_indexer s3://encode-dnase-models/encode.dnase.tasks.tsv \
    --tdb_partition_attribute_for_upsample idr_peak \
    --tdb_partition_thresh_for_upsample 1 \
    --tdb_inputs seq \
    --tdb_input_source_attribute seq \
    --tdb_input_aggregation None \
    --tdb_input_transformation None \
    --tdb_input_flank 500 \
    --tdb_outputs s3://encode-dnase-models/encode.dnase.tasks.tsv \
    --tdb_output_source_attribute fc_bigwig \
    --tdb_output_flank 100 \
    --tdb_output_aggregation mean \
    --tdb_output_transformation asinh \
    --num_inputs 1 \
    --num_outputs 1 \
    --train_chroms chr2 chr3 chr4 chr5 chr6 chr7 chr9 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY \
    --validation_chroms chr8 chr10 \
    --chrom_sizes s3://hg38.chrom.sizes \
    --upsample_ratio_list_train 0.7 \
    --upsample_ratio_list_eval 0.98 \
    --upsample_thresh_list_train 0,0.9 \
    --upsamlpe_thresh_list_eval 0,0.9 \
    --num_train 100000 \
    --num_valid 10000 \
    --num_tasks 723 \
    --threads 20 \
    --max_queue_size 100 \
    --patience 3 \
    --patience_lr 2 \
    --model_hdf5 s3://ENCODE.dnase.regression.0 \
    --architecture_spec functional_basset_regression \
    --use_multiprocessing True

